import { ImageResponse } from "next/og";

// Default share card for the landing page. Per-profile cards are generated by
// `src/app/api/og/[handle]/route.tsx`. Uses the Node runtime to match that
// route (the project runs on the Cloudflare Node-compatible adapter).
export const runtime = "nodejs";
export const contentType = "image/png";
export const alt = "TrueHire — the verified-candidate layer";
export const size = { width: 1200, height: 630 };

export default function OgImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: 72,
          background: "#0a0a0b",
          color: "#f6f5f2",
          fontFamily: "system-ui, -apple-system, sans-serif",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              width: 40,
              height: 40,
              borderRadius: 10,
              background: "#f6f5f2",
              color: "#0a0a0b",
              fontSize: 28,
              fontWeight: 700,
            }}
          >
            ✓
          </div>
          <div style={{ display: "flex", fontSize: 28, fontWeight: 600 }}>
            TrueHire
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
          <div
            style={{
              display: "flex",
              fontSize: 76,
              lineHeight: 1.05,
              fontWeight: 600,
              letterSpacing: "-0.02em",
            }}
          >
            Your resume is gone.
          </div>
          <div
            style={{
              display: "flex",
              fontSize: 76,
              lineHeight: 1.05,
              fontWeight: 600,
              letterSpacing: "-0.02em",
              color: "#8a8a93",
            }}
          >
            Your work still speaks.
          </div>
          <div
            style={{
              display: "flex",
              fontSize: 28,
              color: "#a0a0a8",
              maxWidth: 880,
              marginTop: 8,
            }}
          >
            Costly, verifiable signals instead of AI-tailored resumes — starting
            with years of public code.
          </div>
        </div>

        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            fontSize: 22,
            color: "#8a8a93",
            borderTop: "1px solid #23232a",
            paddingTop: 20,
          }}
        >
          <div style={{ display: "flex", gap: 24 }}>
            <span>Public work</span>
            <span>Employer verification</span>
            <span>Reputation bonds</span>
            <span>Paid audition</span>
          </div>
          <div style={{ display: "flex" }}>truehire.dev</div>
        </div>
      </div>
    ),
    size,
  );
}
