import type { ShortlistCandidateInput } from '@truehire/core';

export const FIXTURE_JD = `Senior product engineer at a Series B SaaS company.
Owning Next.js + TypeScript surfaces backed by a Cloudflare Workers API.
You will ship features end-to-end: design, build, test, deploy.
Must show: TypeScript, React/Next.js, API ownership, testing discipline, CI, and documentation.
Open-source collaboration is a plus.`;

export const FIXTURE_GENERATED_AT = '2026-06-04T12:00:00.000Z';

export const FIXTURE_CANDIDATES: ShortlistCandidateInput[] = [
  {
    handle: 'ada-the-builder',
    name: 'Ada (fixture)',
    profileUrl: '#fixture-ada',
    overallScore: 84,
    signal1: 84,
    signal2: 0,
    totalRepos: 27,
    monthsActive: 46,
    computedAt: '2026-06-03T08:12:00.000Z',
    evidence: [
      {
        repoFullName: 'ada-the-builder/next-orbit',
        stars: 1820,
        commits: 612,
        mergedPrs: 0,
        isAuthor: true,
        primaryLanguage: 'TypeScript',
        weight: 96,
        craftTags: ['CI', 'tests', 'docs', 'releases'],
      },
      {
        repoFullName: 'cloudflare/workers-sdk',
        stars: 3200,
        commits: 41,
        mergedPrs: 9,
        isAuthor: false,
        primaryLanguage: 'TypeScript',
        weight: 71,
        craftTags: ['CI'],
      },
      {
        repoFullName: 'ada-the-builder/edge-router',
        stars: 410,
        commits: 188,
        mergedPrs: 0,
        isAuthor: true,
        primaryLanguage: 'TypeScript',
        weight: 58,
        craftTags: ['CI', 'tests', 'docs'],
      },
      {
        repoFullName: 'vercel/next.js',
        stars: 122000,
        commits: 4,
        mergedPrs: 3,
        isAuthor: false,
        primaryLanguage: 'TypeScript',
        weight: 38,
        craftTags: ['CI'],
      },
    ],
    languages: [
      { language: 'TypeScript', share: 0.74, commits: 1420 },
      { language: 'JavaScript', share: 0.16, commits: 308 },
      { language: 'MDX', share: 0.06, commits: 112 },
      { language: 'Shell', share: 0.04, commits: 70 },
    ],
  },
  {
    handle: 'byteforge',
    name: 'Byteforge (fixture)',
    profileUrl: '#fixture-byteforge',
    overallScore: 77,
    signal1: 77,
    signal2: 0,
    totalRepos: 18,
    monthsActive: 38,
    computedAt: '2026-05-28T19:40:00.000Z',
    evidence: [
      {
        repoFullName: 'byteforge/api-gateway',
        stars: 540,
        commits: 421,
        mergedPrs: 0,
        isAuthor: true,
        primaryLanguage: 'TypeScript',
        weight: 78,
        craftTags: ['CI', 'tests'],
      },
      {
        repoFullName: 'honojs/hono',
        stars: 17000,
        commits: 18,
        mergedPrs: 5,
        isAuthor: false,
        primaryLanguage: 'TypeScript',
        weight: 49,
        craftTags: ['CI'],
      },
      {
        repoFullName: 'byteforge/queue-worker',
        stars: 88,
        commits: 132,
        mergedPrs: 0,
        isAuthor: true,
        primaryLanguage: 'TypeScript',
        weight: 40,
        craftTags: ['CI'],
      },
    ],
    languages: [
      { language: 'TypeScript', share: 0.58, commits: 960 },
      { language: 'Go', share: 0.22, commits: 364 },
      { language: 'Shell', share: 0.12, commits: 198 },
      { language: 'Dockerfile', share: 0.08, commits: 132 },
    ],
  },
  {
    handle: 'rustronaut',
    name: 'Rustronaut (fixture)',
    profileUrl: '#fixture-rustronaut',
    overallScore: 88,
    signal1: 88,
    signal2: 0,
    totalRepos: 22,
    monthsActive: 54,
    computedAt: '2026-06-01T10:05:00.000Z',
    evidence: [
      {
        repoFullName: 'rustronaut/warp-cache',
        stars: 4100,
        commits: 805,
        mergedPrs: 0,
        isAuthor: true,
        primaryLanguage: 'Rust',
        weight: 98,
        craftTags: ['CI', 'tests', 'releases'],
      },
      {
        repoFullName: 'tokio-rs/tokio',
        stars: 26000,
        commits: 32,
        mergedPrs: 11,
        isAuthor: false,
        primaryLanguage: 'Rust',
        weight: 74,
        craftTags: ['CI'],
      },
      {
        repoFullName: 'rustronaut/orbit-rpc',
        stars: 690,
        commits: 312,
        mergedPrs: 0,
        isAuthor: true,
        primaryLanguage: 'Rust',
        weight: 55,
        craftTags: ['CI', 'tests'],
      },
    ],
    languages: [
      { language: 'Rust', share: 0.78, commits: 1840 },
      { language: 'Go', share: 0.12, commits: 282 },
      { language: 'Shell', share: 0.06, commits: 142 },
      { language: 'Python', share: 0.04, commits: 94 },
    ],
  },
  {
    handle: 'first-pr',
    name: 'First-PR (fixture)',
    profileUrl: '#fixture-first-pr',
    overallScore: 49,
    signal1: 49,
    signal2: 0,
    totalRepos: 6,
    monthsActive: 9,
    computedAt: '2026-02-14T14:22:00.000Z',
    evidence: [
      {
        repoFullName: 'first-pr/study-next-app',
        stars: 12,
        commits: 96,
        mergedPrs: 0,
        isAuthor: true,
        primaryLanguage: 'TypeScript',
        weight: 34,
        craftTags: ['docs'],
      },
      {
        repoFullName: 'first-pr/react-todo',
        stars: 3,
        commits: 41,
        mergedPrs: 0,
        isAuthor: true,
        primaryLanguage: 'TypeScript',
        weight: 22,
        craftTags: [],
      },
      {
        repoFullName: 'facebook/react',
        stars: 222000,
        commits: 1,
        mergedPrs: 1,
        isAuthor: false,
        primaryLanguage: 'JavaScript',
        weight: 18,
        craftTags: [],
      },
    ],
    languages: [
      { language: 'TypeScript', share: 0.68, commits: 196 },
      { language: 'JavaScript', share: 0.22, commits: 64 },
      { language: 'CSS', share: 0.1, commits: 28 },
    ],
  },
];
