import { PDFDocument, type PDFFont, type PDFPage, rgb, StandardFonts } from 'pdf-lib';
import type { Artifact } from './types';

// A4 in points.
const W = 595;
const H = 842;
const M = 50;

const INK = rgb(0.1, 0.1, 0.12);
const MUTED = rgb(0.45, 0.45, 0.52);
const FAINT = rgb(0.62, 0.62, 0.68);
const ACCENT = rgb(0.36, 0.4, 0.95);
const TRACK = rgb(0.9, 0.9, 0.93);
const RULE = rgb(0.86, 0.86, 0.9);

const TOOL_LABEL: Record<string, string> = {
  'claude-code': 'Claude Code',
  cursor: 'Cursor',
  codex: 'Codex',
};

function fmtDate(ms: number): string {
  return new Date(ms).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

/** Render the AI build profile artifact to a one-page A4 PDF (Uint8Array). */
export async function generateReport(artifact: Artifact): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle('TrueHire — AI Build Profile');
  doc.setCreator('truehire CLI');
  const page = doc.addPage([W, H]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const text = (s: string, x: number, y: number, size: number, f: PDFFont, color = INK) =>
    page.drawText(s, { x, y, size, font: f, color });
  const right = (s: string, xRight: number, y: number, size: number, f: PDFFont, color = INK) =>
    text(s, xRight - f.widthOfTextAtSize(s, size), y, size, f, color);
  const rule = (y: number) =>
    page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 1, color: RULE });

  // ── header ──
  text('TrueHire', M, H - M, 13, bold, ACCENT);
  right(fmtDate(artifact.generatedAt), W - M, H - M, 10, font, MUTED);
  let y = H - M - 30;
  text('AI Build Profile', M, y, 26, bold, INK);
  y -= 18;
  text('How you build with AI · self-attested', M, y, 11, font, MUTED);

  // ── composite ──
  y -= 50;
  const composite = artifact.composite == null ? '—' : String(artifact.composite);
  text(composite, M, y, 46, bold, INK);
  const cw = bold.widthOfTextAtSize(composite, 46);
  text('/ 100', M + cw + 8, y + 6, 16, font, MUTED);
  text('AI Build Index', M + cw + 8, y - 12, 10, font, FAINT);
  right(
    `${Math.round(artifact.dataCompleteness * 100)}% data completeness`,
    W - M,
    y + 6,
    11,
    font,
    MUTED
  );
  const tools = artifact.toolsDetected
    .map((t) => `${TOOL_LABEL[t.tool] ?? t.tool} (${t.fidelity})`)
    .join('   ');
  right(tools, W - M, y - 12, 9, font, FAINT);

  // ── dimensions ──
  y -= 44;
  text('DIMENSIONS', M, y, 9, bold, FAINT);
  y -= 18;
  const barX = 200;
  const barW = W - M - barX - 36;
  for (const d of artifact.dimensions) {
    text(d.name, M, y, 11, font, INK);
    page.drawRectangle({ x: barX, y: y - 1, width: barW, height: 6, color: TRACK });
    if (d.score != null) {
      page.drawRectangle({
        x: barX,
        y: y - 1,
        width: (barW * Math.max(0, Math.min(100, d.score))) / 100,
        height: 6,
        color: ACCENT,
      });
    }
    right(
      d.score == null ? '—' : String(d.score),
      W - M,
      y,
      11,
      bold,
      d.score == null ? FAINT : INK
    );
    y -= 22;
  }

  // ── top projects ──
  if (artifact.projects.length > 0) {
    y -= 12;
    const total = artifact.signals.projectCount ?? artifact.projects.length;
    text(`TOP PROJECTS · AI USED ACROSS ${total} PROJECTS`, M, y, 9, bold, FAINT);
    y -= 16;
    rule(y + 4);
    y -= 12;
    for (const p of artifact.projects.slice(0, 10)) {
      text(p.name.slice(0, 32), M, y, 10, font, INK);
      text(p.tools.map((t) => TOOL_LABEL[t] ?? t).join(', '), 300, y, 9, font, FAINT);
      right(`${p.sessions} sessions`, W - M, y, 10, font, MUTED);
      y -= 17;
    }
  }

  // ── footer ──
  rule(M + 40);
  drawFooter(page, font, artifact.cliVersion);
  return doc.save();
}

function drawFooter(page: PDFPage, font: PDFFont, cliVersion: string): void {
  const lines = [
    'Self-attested. Computed locally from your AI-coding tools (Claude Code, Cursor, Codex) — no',
    'prompt text, code, or file paths leave your machine. Contributes 0 to the verified TrueHire score.',
  ];
  let fy = M + 24;
  for (const line of lines) {
    page.drawText(line, { x: M, y: fy, size: 8, font, color: FAINT });
    fy -= 11;
  }
  page.drawText(`Generated by truehire CLI v${cliVersion}`, {
    x: M,
    y: M,
    size: 8,
    font,
    color: FAINT,
  });
}
